services:
  postgres:
    container_name: db-postgres
    image: "postgres:alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_PORT=${PG_PORT}
    env_file:
      - ./.env
    networks:
      - home

  web:
    build: .
    command: uvicorn web_app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_PORT=${PG_PORT}
    env_file:
      - ./.env
    networks:
      - home

volumes:
  postgres_data:
  test_postgres_data:

networks:
  home:
    driver: bridge
