services:
  postgres:
    container_name: db-postgres
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "8111:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    networks:
      - home

  test_postgres:
    container_name: test-db-postgres
    image: postgres:14
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/
    ports:
      - "8112:5433"
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    networks:
      - home

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    networks:
      - home

  # alembic:
  #   build: .
  #   command: alembic upgrade head
  #   depends_on:
  #     - postgres
  #   environment:
  #     - POSTGRES_USER=${PG_USER}
  #     - POSTGRES_PASSWORD=${PG_PASS}
  #     - POSTGRES_DB=${PG_NAME}
  #   networks:
  #     - home

  ipython:
    build: .
    command: ipython
    volumes:
      - .:/code
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    networks:
      - home

volumes:
  postgres_data:
  test_postgres_data:

networks:
  home:
    external: true
