"""indexing

Revision ID: 0d938e39fdb1
Revises: e46ea39ce1b0
Create Date: 2024-09-09 19:57:49.067178

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d938e39fdb1"
down_revision: Union[str, None] = "e46ea39ce1b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("user_balance", "users", ["balance"], unique=False)
    op.create_index(
        "user_block_status", "users", ["block_status"], unique=False
    )
    op.create_index("user_email", "users", ["email"], unique=False)
    op.create_index(
        "user_last_activity_at", "users", ["last_activity_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("user_last_activity_at", table_name="users")
    op.drop_index("user_email", table_name="users")
    op.drop_index("user_block_status", table_name="users")
    op.drop_index("user_balance", table_name="users")
    # ### end Alembic commands ###
