"""added role

Revision ID: f57b2a8dc82c
Revises: 0d938e39fdb1
Create Date: 2024-09-11 12:32:24.275062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f57b2a8dc82c"
down_revision: Union[str, None] = "0d938e39fdb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "USER", name="userroleenum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_activity_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("block_status", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("user_balance", "users", ["balance"], unique=False)
    op.create_index(
        "user_block_status", "users", ["block_status"], unique=False
    )
    op.create_index("user_email", "users", ["email"], unique=False)
    op.create_index(
        "user_last_activity_at", "users", ["last_activity_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("user_last_activity_at", table_name="users")
    op.drop_index("user_email", table_name="users")
    op.drop_index("user_block_status", table_name="users")
    op.drop_index("user_balance", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
